sudo: required
services:
  - docker

before_install:
  - docker_build -t edpsyk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edpsyk/react-test npm test

after_success:
  - docker build -t edpsyk/multi-client ./client
  - docker build -t edpsyk/multi-nginx ./nginx
  - docker build -t edpsyk/multi-server ./server
  - docker build -t edpsyk/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push edpsyk/multi-client
  - docker push edpsyk/multi-nginx
  - docker push edpsyk/multi-server
  - docker push edpsyk/multi-worker
